adapted to dCache versions ≥ 2.8
In dCache 2.8 the Administration Shell commands and their ouputs were completely
overhauled.

• Adapted the program to dCache versions ≥ 2.8, no longer supporting older ones.
• Made the parsing and regular expressions more robust.
• Update the link groups before retrieving their listing.

Signed-off-by: Christoph Anton Mitterer <mail@christoph.anton.mitterer.name>

diff --git a/adjust_space_reservation_sizes_to_their_respective_link_groups b/adjust_space_reservation_sizes_to_their_respective_link_groups
--- a/adjust_space_reservation_sizes_to_their_respective_link_groups
+++ b/adjust_space_reservation_sizes_to_their_respective_link_groups
@@ -25,35 +25,44 @@ fi
 
 
 #********************************************************************************
-#*** Adjust The Space Token Sizes To Their Respective Link Group              ***
+#*** Adjust The Space Reservation Sizes To Their Respective Link Groups       ***
 #********************************************************************************
-#get listing from the space manager
-space_manager_listing="$( printf 'cd SrmSpaceManager\nls\n'  |  /usr/local/bin/dcache_admin )"
+#get listings from the space manager
+link_groups_listing="$( printf 'cd SrmSpaceManager\nupdate link groups -blocking\nls link groups\n'  |  /usr/local/bin/dcache_admin )"
 if [ $? -ne 0 ]; then #error handling
-	printf 'Error: Could not get listing from the space manager.\n' >&2
+	printf 'Error: Could not get link groups listing from the space manager.\n' >&2
 	exit 1
 fi
+link_groups_listing="$( printf "%s" "${link_groups_listing}" | sed '0,/^[[:space:]]*FLAGS[[:space:]][[:space:]]*CNT[[:space:]][[:space:]]*RESVD[[:space:]][[:space:]]*AVAIL[[:space:]][[:space:]]*FREE[[:space:]][[:space:]]*UPDATED[[:space:]][[:space:]]*NAME[[:space:]]*$/d; /^$/Q; s/^ *//; s/   */ /g; s/ + / /g; s/ = / /g' )"
+
+space_reservations_listing="$( printf 'cd SrmSpaceManager\nls spaces\n'  |  /usr/local/bin/dcache_admin )"
+if [ $? -ne 0 ]; then #error handling
+	printf 'Error: Could not get space reservations listing from the space manager.\n' >&2
+	exit 1
+fi
+space_reservations_listing="$( printf '%s' "${space_reservations_listing}"  |  sed '0,/^[[:space:]]*TOKEN[[:space:]][[:space:]]*LINKGROUP[[:space:]][[:space:]]*RETENTION[[:space:]][[:space:]]*LATENCY[[:space:]][[:space:]]*ALLO[[:space:]][[:space:]]*USED[[:space:]][[:space:]]*FREE[[:space:]][[:space:]]*SIZE[[:space:]][[:space:]]*DESCRIPTION[[:space:]]*$/d; /^$/Q; s/^ *//; s/   */ /g; s/ + / /g; s/ = / /g' )"
+
 
 #construct adjustment commands
 {
-	printf 'cd SrmSpaceManager\n'
+	printf '..\ncd SrmSpaceManager\n'
+
+	printf '%s\n' "$space_reservations_listing" \
+	| while read space_reservation; do
+		space_reservation_token="$( printf '%s' "${space_reservation}"  |  cut -d ' ' -f 1 )"
+		space_reservation_link_group="$( printf '%s' "${space_reservation}"  |  cut -d ' ' -f 2 )"
+		space_reservation_size="$( printf '%s' "${space_reservation}"  |  cut -d ' ' -f 8 )"
 	
-	printf '%s\n' "${space_manager_listing}"  |  grep ' linkGroupId:[[:digit:]][[:digit:]]* ' \
-	| while read space_token_listing; do
-		space_token_id="$( printf '%s' "${space_token_listing}"  |  cut -d ' ' -f 1 )"
-		link_group_id="$( printf '%s' "${space_token_listing}"  |  sed 's/^.* linkGroupId:\([[:digit:]][[:digit:]]*\) .*$/\1/' )"
-		space_token_size="$( printf '%s' "${space_token_listing}"  |  sed 's/^.* size:\([[:digit:]][[:digit:]]*\) .*$/\1/' )"
-		
-		link_group_available_space="$( printf '%s' "${space_manager_listing}"  |  grep "^${link_group_id} Name:"  |  sed 's/^.* AvailableSpace:\(-*[[:digit:]][[:digit:]]*\) .*$/\1/' )"
-		
-		printf 'update space reservation -size=%s %s\n' "$((${space_token_size}+${link_group_available_space}))" "${space_token_id}"
+		link_group_available_space="$( printf '%s' "${link_groups_listing}"  |  grep "${space_reservation_link_group}[[:space:]]*$"  |  cut -d ' ' -f 4 )"
+	
+		printf 'update space -size=%s %s\n' "$((${space_reservation_size}+${link_group_available_space}))" "${space_reservation_token}"
 	done
-	
+
 	printf '..\nlogoff\n'
 } \
 | /usr/local/bin/dcache_admin > /dev/null
 if [ $? -ne 0 ]; then #error handling
-	printf 'Error: Could not adjust the space token sizes to their respective link group.\n' >&2
+	printf 'Error: Could not adjust the space token sizes to their respective link groups.\n' >&2
 	exit 1
 fi
 
@@ -77,7 +86,7 @@ exit 0
 
 
 
-#Copyright © 2012–2013, Christoph Anton Mitterer <mail@christoph.anton.mitterer.name>.
+#Copyright © 2012–2015, Christoph Anton Mitterer <mail@christoph.anton.mitterer.name>.
 #All rights reserved.
 #
 #
