redirect error messages to stderr
• Where missing, redirect error messages to stderr.

Signed-off-by: Christoph Anton Mitterer <mail@christoph.anton.mitterer.name>

diff --git a/adjust_space_reservation_sizes_to_their_respective_link_groups b/adjust_space_reservation_sizes_to_their_respective_link_groups
--- a/adjust_space_reservation_sizes_to_their_respective_link_groups
+++ b/adjust_space_reservation_sizes_to_their_respective_link_groups
@@ -46,7 +46,7 @@ if [ $# -eq 1 ]; then
 		;;
 	
 	(*)
-		printf 'Error: Invalid arguments.\n'
+		printf 'Error: Invalid arguments.\n' >&2
 		exit 2
 	esac
 fi
@@ -54,7 +54,7 @@ fi
 
 #check whether the correct number of arguments are specified
 if [ $# -ne 0 ]; then
-	printf 'Error: Invalid arguments.\n'
+	printf 'Error: Invalid arguments.\n' >&2
 	exit 2
 fi
 
