adapted to new dump file naming schema (filename’s date)
ATLAS recently changed the dump file naming schema by expecting the filename’s
date to be at the time interval’s start instead of the dump file’s creation time
(that is the time interval’s end).

• Adapted the filename’s date to the new dump file naming schema.

Signed-off-by: Christoph Anton Mitterer <mail@christoph.anton.mitterer.name>

diff --git a/create_and_rotate_atlas_rucio_chimera_dumps b/create_and_rotate_atlas_rucio_chimera_dumps
--- a/create_and_rotate_atlas_rucio_chimera_dumps
+++ b/create_and_rotate_atlas_rucio_chimera_dumps
@@ -13,6 +13,15 @@ PATH='/usr/sbin:/sbin:/usr/bin:/bin'
 
 
 #*******************************************************************************
+#*** Default Values                                                          ***
+#*******************************************************************************
+#Note: This must be kept aligned with chimera_find’s default value of the parameter “DATE”.
+DEFAULT_CHIMERA_FIND_DATE_INTERVAL='1 day ago'
+
+
+
+
+#*******************************************************************************
 #*** Print Program Usage                                                     ***
 #*******************************************************************************
 print_usage()
@@ -68,14 +77,25 @@ if [ ! -x "$( which chimera_find )" ]; then
 	exit 2
 fi
 
+#check for “psql”
+if [ ! -x "$( which psql )" ]; then
+	printf 'Error: psql is not available.\n' >&2
+	exit 2
+fi
+
 
 
 
 #*******************************************************************************
 #*** Create And Rotate ATLAS Rucio Chimera Dumps                             ***
 #*******************************************************************************
-#determine the current UTC date
-date="$(date -u +%Y%m%d)"
+#determine the UTC date at the time interval’s start
+date="$( printf "SELECT EXTRACT(epoch FROM INTERVAL '%s');" "${DATE:-"${DEFAULT_CHIMERA_FIND_DATE_INTERVAL}"}"  |  psql --no-align --tuples-only --field-separator=' ' 2> /dev/null )"
+if [ $? -ne 0  -o  -z "${date}" ]; then
+	printf 'Error: Could not parse the time interval “%s”.\n' "${DATE:-"${DEFAULT_CHIMERA_FIND_DATE_INTERVAL}"}" >&2
+	exit 2
+fi
+date="$( date -u -d "@$(( $( date -u +%s ) + ${date} ))" +%Y%m%d )"
 
 
 #process each base directory
