create a Chimera dump for each base directory
• Added a check whether “chimera_find” is available.
• Create a Chimera dump for each base directory.
  If that fails, try to remove the created file.

Signed-off-by: Christoph Anton Mitterer <mail@christoph.anton.mitterer.name>

diff --git a/create_and_rotate_atlas_rucio_chimera_dumps b/create_and_rotate_atlas_rucio_chimera_dumps
--- a/create_and_rotate_atlas_rucio_chimera_dumps
+++ b/create_and_rotate_atlas_rucio_chimera_dumps
@@ -62,6 +62,13 @@ fi
 maximum_dump_file_age="$1"
 
 
+#check for “chimera_find”
+if [ ! -x "$( which chimera_find )" ]; then
+	printf 'Error: chimera_find is not available.\n' >&2
+	exit 2
+fi
+
+
 
 
 #*******************************************************************************
@@ -108,6 +115,17 @@ while [ $# -ge 2 ]; do
 		printf 'Error: “%s/dump/dump_%s” exists already. Ignoring “%s”.\n' "${base_directory}" "${date}" "${base_directory}" >&2
 		exit_status=1
 		continue
+	fi
+	
+	
+	#create a Chimera dump for the base directory
+	chimera_find "${base_directory}/dump/dump_${date}" "${base_directory}" /
+	if [ $? -ne 0 ]; then #error handling
+		printf 'Error: An error occurred while creating a Chimera dump for the base directory “%s”.\n' "${base_directory}" >&2
+		exit_status=1
+		
+		#try to remove the created dump file
+		rm -f "${base_directory}/dump/dump_${date}"
 	fi
 done
 
