check each destination file whether it exists already
• Check each destination file whether it exists already and ignore the base
  directories of those that do.

Signed-off-by: Christoph Anton Mitterer <mail@christoph.anton.mitterer.name>

diff --git a/create_and_rotate_atlas_rucio_chimera_dumps b/create_and_rotate_atlas_rucio_chimera_dumps
--- a/create_and_rotate_atlas_rucio_chimera_dumps
+++ b/create_and_rotate_atlas_rucio_chimera_dumps
@@ -102,6 +102,13 @@ while [ $# -ge 2 ]; do
 			continue
 		fi
 	fi
+	
+	#check whether the destination file exists
+	if [ -e "${base_directory}/dump/dump_${date}" ]; then
+		printf 'Error: “%s/dump/dump_%s” exists already. Ignoring “%s”.\n' "${base_directory}" "${date}" "${base_directory}" >&2
+		exit_status=1
+		continue
+	fi
 done
 
 
